# targetTemplates:
#   ios-app:
#     type: application
#     platform: [iOS]

# name: MyProject
# options:
#   bundleIdPrefix: com.myapp
# targets:
#   MyApp:
#     templates: [ios-app]
#     deploymentTarget: "10.0"
#     sources: [MyApp]

name: ModularPodTest
options:
  bundleIdPrefix: com.adereskita
targets:
  ModularPodTest:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - ModularPodTest
      # - path: ModularPodTest